language: python
python:
  - "2.6"
  - "2.7"
sudo: required
compiler:
  - gcc
  - clang
before_install: sh install-pll.sh
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - make install
script: make tests
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang