language: python
python:
  - "2.6"
  - "2.7"
sudo: required
compiler:
  - gcc
  - clang
before_install: sh install-pll.sh
install: CC=gcc-4.8 make install
script: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make tests
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
